### ISSUE TITLE
As an admin, I want a quick overview of changes made specifically to a customer account, so that I can easily see the actions taken by other admins.

### ISSUE THREAD

**Issue by IsabelHaataja** [KYH-Net23/AdminCustomerSettingService#10]
Authors: Kimmo Ahola & Isabel Haataja

## Acceptance Criteria:
- [ ]  The changes made by an admin account on a specific customer account needs to be visible.
- [ ] There needs to be a “show more/details” button to get an overview.
- [ ] If there is no history at all, the page should display a special message.
- [ ] Only logged in admin accounts should see this overview page.
- [ ] The types of history actions are: changes to customer profile, changes to customer groups, changes to customer order history, changes to invoices.
- [ ] The history should be displayed in chronological order in a list.
- [ ] History can not be edited.

## Tasks:
- [ ] **Task 1:** Implement UI for edits made on customers account.
- [ ] Implement a “show more/details” button.
- [ ] Implement an accordion “show more/details” button to get an overview of the history.
- [ ] Implement a message that displays when there is not any history yet.
- [ ] **Task 2:** Implement a data model
- Action type Enum (PROFILE_CHANGE, GROUP_CHANGE, ORDER_CHANGE, INVOICE_CHANGE)
- Date of change
- The admin User ID
- Content/Reason (nullable)
- [ ] **Task 3:** Implement sorting so that the history displays chronologically.
- [ ] **Task 4:** Implement an API to save changes to a database.

## Activity Diagram: 
![Image](https://github.com/user-attachments/assets/539c9fc7-8d42-4f68-b0e2-6a8a5fe7bb71)

## Test Cases:
- [ ] **Case 1:**
Prerequisites: The admin navigates to a customer that has a history with 2 or more activities.
Steps:
View the first item on the list of history
Compare the date of change with the second activity.
Expected Results: The first item on the list should be the most recently added activity.
