### ISSUE TITLE
As an admin I want to be able to look at customers' purchase statistics, so that I can plan inventory and campaigns.

### ISSUE THREAD

**Issue by IsabelHaataja** [KYH-Net23/AdminCustomerSettingService#15]
Authors: Kimmo Ahola & Isabel Haataja

## Acceptance Criteria:

- [ ] The admin can see all customers' purchases.
- [ ] A pie chart over product categories.
- [ ] A line chart for purchases over time.
- [ ] The admin can see what products has been purchased, at what time and for what price.

## Tasks:

- [ ] **Task 1:** Implement a chart provider that uses HighCharts .NET/Js.
- [ ] **Task 2:** Implement an Order Provider API if it doesn’t already exist.
- [ ] **Task 3:** Implement a sales report creation provider that creates reports in different file formats (pdf, csv).
- [ ] **Task 4:** Implement a Report Data View Model
- Demographics
- Gender
- Location
- Total Spent
- Number of Purchases
- Payment Method

## Activity Diagram: 
![Image](https://github.com/user-attachments/assets/7b158dbd-5f9a-407d-930e-d6bf4f172c72)

## Test Cases:
- [ ] **Case 1:**
Prerequisites: Admin tries to download a sales report csv.
Steps:
1. Admin chooses file format csv
2. Admin presses the “download report” button.
Expected Results: A csv sales report file is generated and downloaded.

-  [ ] **Case 2:**
Prerequisites: Admin tries to create a pie chart.
Steps: 
1. Admin chooses a demographic.
2. Admin presses the “apply filter” button.
Expected Results: 
A pie chart is created, sorted by the chosen demographic. Each pie slice shows purchase categories.
If no data is available or the chart creation fails, display an error message.

- [ ] **Case 3:**
Prerequisites: Admin tries to create a line chart.
Steps: 
1. Admin selects start and end date.
2. Admin presses the “apply filter” button.
Expected Results: 
A line chart is created with purchase volume per day visible.
If no data is available or the chart creation fails, display an error message.

- [ ] **Case 4:**
Prerequisite: User is not logged in as an admin.
Steps:
1. Try to access the page.
Expected Results:
Redirect the user to an unauthorized access page.
Display an error message.
