### ISSUE TITLE
As an Admin, I want to view a specific customer’s profile details.

### ISSUE THREAD

**Issue by acerd44** [KYH-Net23/AdminCustomerSettingService#16]
**Made by Hossén & Oliver**

## Acceptance Criteria
- [ ] Only admins should be able to access/view customer information.
- [ ] Admin should be able to click on a ‘Details’ button tied on a specific customer which redirects to the customer's details page.
- [ ] The page should display relevant and correct information about the customer.
- [ ] Implement API endpoint for fetching an customer from the database
- [ ] Implement a method for mapping the Customer Entity received from the database to return an Customer Details model.
- [ ] Implement authorization
- [ ] Implement UI/frontend
  - [ ] Display the information on the page.
## Tasks
- [ ] Implement Customer Data Model
  - Customer Id
  - First Name
  - Last Name
  - Email
  - Password
  - Address
  - Phone Number
  - City/Province
  - Zip code
  - Country
  - Status
- [ ] Implement Customer Details Model
  - Customer Id
  - First Name
  - Last Name
  - Email
  - Address
  - Phone Number
  - City/Province
  - Zip code
  - Country
  - Status
## Test Cases
- [ ] Verify that the customer details are loaded and displayed properly.
  - Prerequisites: 
    - User is logged in as an administrator.
    - User is navigated to the ‘All customers’ page.
  - Steps
    - Click on the "Details" button of a specific customer.
  - Expected result: 
    - The system displays the customer information on the page.
- [ ] Verify that only admins can access and view customer information.
  - Prerequisites:
    - The user attempting to access the page (presumably by URL) is not an administrator or is not logged in.
  - Steps:
      - Enter the URL for the customer's details page.
  - Expected results:
      - The user is redirected to a 401 error code page (unauthorized).
      - Display an error message.
- [ ] Verify that an error message is received when the customer’s details could not be loaded correctly.
  - Prerequisites:
    - User is logged in as an administrator.
    - User is navigated to the ‘All customers’ page.
  - Steps
    - Click on the "Details" button of a specific customer.
  - Expected results:
    - The system displays an error message "customer details could not be loaded correctly".
## Activity Diagram
![Image](https://i.imgur.com/Nfbhiq9.png)
